planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    planner_plugins: ["GridBased"]
    costmap_update_timeout: 1.0
    GridBased:
      plugin: "astar_planner::AStarPlanner"
      print_runtime: true
      tolerance: 0.5
      max_iterations: 99999
      tie_breaker: 1.001
      allow_unknown: true
      cost_function_type: 2

global_occ_map:
  ros__parameters:

    print_timer: false       # If enabled, print debug information such as timing information

    update_local_map_frequency: 10.0 # [Hz] Frequency to update the local map
    viz_map_frequency: 2.0   # [Hz] Frequency to visualize the local map

    global_map: 
      size_x: 60.0  # [m]
      size_y: 60.0  # [m]
      size_z: 10.0  # [m]

    local_map:  # Local map used by planner
      size_x: 20.0  # [m]
      size_y: 20.0  # [m]
      size_z: 5.0   # [m]

    prob_map:  # Occupancy map parameters
      # Probabilistic map
      prob_miss_log: 0.35 # 
      prob_hit_log: 0.78  # 
      clamp_min_log: 0.12 # 
      clamp_max_log: 0.90 # 
      occupancy_threshold_log: 0.5 # 

      resolution: 0.1   # [m] Resolution of voxel
      static_inflation: 0.2    # [m] Static obstacle inflation
      ground_height: 0.0  # [m] Height considered to be ground. Anything below this value leads to a potential collision
      # dynamic_inflation: 0.6    # Unused [m] Dynamic obstacle inflation
      max_range: 5.0   # [m] Maximum range of sensor

    # Passthrough filter for input point cloud
    cloud_in_min_z: -0.5 # [m] Minimum height for point cloud to be included in map
    cloud_in_max_z: 5.0 # [m] Maximum height for point cloud to be included in map

    # Noise filter by checking clusters
    noise_search_radius: 0.17  # Radius to search for neighbouring points
    noise_min_neighbors: 1 # Minimum number of neighbors within 'search_radius' to be a valid point


local_occ_map:
