/traj_server:
  ros__parameters:
    origin_frame: world
    base_link_frame: base_link

    # Default take_off height
    takeoff_height: 1.0 # [m]

    # Frequency for timers
    set_offb_ctrl_freq: 4.0  #[ Hz] Offboard control mode publish frequency
    pub_odom_freq: 30.0  # [Hz] Publish odometry frequency 
    pub_cmd_freq: 30.0  # [Hz] Publish control input command frequency