/**: 
  ros__parameters:
    fake_drone:
      drone_id: 0

      global_frame: "world"
      local_map_origin: "local_map_origin"
      uav_frame: "base_link"

      state_update_frequency: 50.0  # [Hz] Frequency at which state is published
      tf_broadcast_frequency: 30.0  # [Hz] Frequency at which tf is broadcasteds

      t_unit: 0.1

      init:
        x: 0.0
        y: 0.0
        z: 0.0
