/**: 
  ros__parameters:
    fake_drone:
      state_update_frequency: 2.0  # [Hz] Frequency at which state is published
      odom_update_frequency: 30.0  # [Hz] Frequency at which odometry is published