/**: 
  ros__parameters:
    navigator:
      local_map_frame: "local_map_origin"
      global_frame: "world"

      planner_frequency: 5.0            # [Hz] Frequency at which plan is generated
      generate_voronoi_frequency: 30.0  # [Hz] Frequency at which voronoi is generated

      planner: 
        verbose_print: true  # If enabled, print debug information such as timing information
        goal_tolerance: 0.3   # [m] Tolerance for goal execution to be complete
        plan_once: false       # Only plan once
        t_unit: 0.1           # [s] Duration of each time unit           
        line_of_sight_smooth: false # Enables line of sight smoothing of raw A* path 

      min_jerk_trajectory:
        front_end_stride: 5 # Stride to sample front-end path for trajectory generation

      reservation_table:
        inflation: 0.4    # [m] buffer for reservation table in spatial domain
        time_buffer: 0.3  # [s] buffer for reservation table in time domain
        window_size: -1  # [voxels] Reserve only up to a given number of points on plan. Negative numbers reserve the whole plan.
