/**: 
  ros__parameters:
    navigator:

      planner: 
        verbose_print: false  # If enabled, print debug information such as runtime 
        plan_once: false       # Only plan once
        goal_tolerance: 0.5   # [m] Tolerance for goal execution to be complete
        t_unit: 0.1           # [s] Duration of each time unit           

      point_goal_height: 0.75 #[m] Height to send point goal

      pub_state_frequency: 10.0 # [Hz] Frequency at which state is published
      planner_frequency: 10.0  # [Hz] Frequency at which plan is generated
      # generate_voronoi_frequency: 5.0  # [Hz] Frequency at which voronoi is generated

      planner_recovery_timeout: 3.0 # [s] UNIMPLEMENTED Timeout before planner recovery behaviour is executed

      # plan_method options
      # 0: COMMLESS_MINCO 
      # 1: COMMLESS_MPC 
      # 2: COMM_MINCO
      plan_method: 1

      enable_dbg_cmds: false
      dbg_fixed_yaw: 0.0 # [rad] Fixed yaw for debugging, only active when yaw_ctrl_flag is set to false
      dbg_fixed_yaw_rate: 1.57 # [rad] Fixed yaw for debugging, only active when yaw_ctrl_flag is set to false
      p_x: 0.0
      p_y: 0.0
      p_z: 0.0

      v_x: 0.0
      v_y: 1.0
      v_z: 0.0 

      a_x: 0.0
      a_y: 0.0
      a_z: 0.0

      mpc:
        ctrl_samp_freq: 30.0 #[Hz] Control sample frequency. The rate at which MPC predicted state is sampled
        ref_path_samp_interval: 1
        # Yaw control
        yaw_ctrl_flag: true # Control the yaw
        yaw_lookahead_dist: 12 # [mpc sample points] Lookahead distance for calculating yaw
        # MPC parameters
        horizon: 15
        time_step: 0.1 #[s]
        # Objective Weights
        R_p: 1000.0 # Error from reference position
        R_v: 0.0  # Velocity magnitude
        R_a: 0.0  # Acceleration magnitude
        R_u: 0.0  # Control magnitude
        R_u_con: 0.2  # Continuity in controls
        R_pN: 2000.0 # Terminal position
        R_vN: 1000.0 # Terminal velocity
        R_aN: 1000.0 # Terminal acceleration
        
        # # # State bounds
        # vx_min: -0.5
        # v_max: 0.5
        # a_min: -6.0
        # a_max: 6.0
        # # Control bounds
        # u_min: -20.0
        # u_max: 20.0
        vx_min:     -0.35
        vy_min:     -0.35
        vz_min:     -0.35
        vx_max:      0.35
        vy_max:      0.35
        vz_max:      0.35

        ax_min:     -10.0
        ay_min:     -10.0
        az_min:     -10.0
        ax_max:      10.0
        ay_max:      10.0
        az_max:      10.0

        ux_min:     -20.0
        uy_min:     -20.0
        uz_min:     -20.0
        ux_max:      20.0
        uy_max:      20.0
        uz_max:      20.0

      sfc:
        bbox_x: 1.0
        bbox_y: 2.0
        bbox_z: 1.0

      reservation_table:
        inflation: 1.0    # [m] buffer for reservation table in spatial domain
        time_buffer: 1.0  # [s] buffer for reservation table in time domain
        window_size: 30  # [voxels] Reserve only up to a given number of points on plan. Negative numbers reserve the whole plan.
