/**: 
  ros__parameters:
    navigator:

      planner: 
        verbose_print: false  # If enabled, print debug information such as runtime 
        plan_once: false       # Only plan once
        goal_tolerance: 0.5   # [m] Tolerance for goal execution to be complete
        t_unit: 0.1           # [s] Duration of each time unit           

      pub_state_frequency: 10.0 # [Hz] Frequency at which state is published
      planner_frequency: 15.0  # [Hz] Frequency at which plan is generated
      generate_voronoi_frequency: 30.0  # [Hz] Frequency at which voronoi is generated

      planner_recovery_timeout: 3.0 # [s] Timeout before planner recovery behaviour is executed

      # plan_method options
      # 0: COMMLESS_MINCO 
      # 1: COMMLESS_MPC 
      # 2: COMM_MINCO
      plan_method: 1

      mpc:
        ctrl_samp_freq: 25.0 #[Hz] Control sample frequency. The rate at which MPC predicted state is sampled
        ref_path_samp_interval: 1
        # MPC parameters
        horizon: 15
        time_step: 0.1 #[s]
        # Objective Weights
        R_p: 1000.0
        R_v: 0.0
        R_a: 0.0
        R_u: 0.0 
        R_u_con: 0.2
        R_pN: 1000.0
        R_vN: 1000.0
        R_aN: 1000.0
        # State bounds
        v_min: -10.0
        v_max: 10.0
        a_min: -20.0
        a_max: 20.0
        # Control bounds
        u_min: -50.0
        u_max: 50.0

      sfc:
        bbox_x: 1.0
        bbox_y: 2.0
        bbox_z: 1.0

      min_jerk_trajectory:
        front_end_stride: 5 # Stride to sample front-end path for trajectory generation

      reservation_table:
        inflation: 1.0    # [m] buffer for reservation table in spatial domain
        time_buffer: 1.0  # [s] buffer for reservation table in time domain
        window_size: 30  # [voxels] Reserve only up to a given number of points on plan. Negative numbers reserve the whole plan.
