/**:
  ros__parameters:
    plugin_denylist:
      # common
      - safety_area
      # extras
      - image_pub
      - vibration
      - distance_sensor
      - rangefinder
      - wheel_odometry
      - guided_target

    # plugin_allowlist:
    #   - 'sys_*'
