/**: 
  ros__parameters:
    voxel_map:

      debug_input_entire_map: false
      entire_pcd_map_topic: "/fake_map"

      dyn_obs:
        mark_in_occ_map: false
        time_vel: 0.75

      verbose_print: false       # If enabled, print debug information such as timing information

      map_slicing: # 2D boolean map slices used for voronoi generation
        # min_height_cm:    40    # [cm] Minimum slice height
        # max_height_cm:    320   # [cm] Maximum slice height
        # z_sep_cm:  40    # [cm] Separation between slices
        min_height_cm:    50    # [cm] Minimum slice height
        max_height_cm:    200   # [cm] Maximum slice height
        z_sep_cm:  50    # [cm] Separation between slices

      global_map: 
        # size_x: 50.0  # [m]
        # size_y: 50.0  # [m]
        # size_z: 10.0  # [m]
        size_x: 30.0  # [m]
        size_y: 30.0  # [m]
        size_z: 10.0  # [m]

      local_map:  # Local map used by planner
        size_x: 10.0  # [m]
        size_y: 10.0  # [m]
        size_z: 10.0   # [m]
        update_local_map_frequency: 5.0 # [Hz] Frequency to update the local map
        viz_map_frequency: 1.0   # [Hz] Frequency to visualize the local map

      occ_map:  # Occupancy map parameters
        resolution: 0.1   # [m] Resolution of voxel
        dynamic_inflation: 0.6    # [m] Dynamic obstacle inflation
        static_inflation: 0.4    # [m] Static obstacle inflation
        ground_height: 0.0  # [m] Height considered to be ground. Anything below this value leads to a potential collision
        max_range: 7.0   # [m] Maximum range of sensor

      collision_check: # For visualizing collision with static obstacles
        enable: false    # Enable checking of collisions
        warn_radius: 0.25  # [m]  Distance to collision to display warning sphere
        fatal_radius: 0.14  # [m] Distance to collision to display fatal sphere
        check_collision_frequency: 15.0 # [Hz]  Frequency to check for collision
