/**:
  ros__parameters:
    trajectory_type: MINCO

    # Frequency for timers
    set_offb_ctrl_freq: 5.0  #[ Hz] Offboard control mode publish frequency
    pub_state_freq: 50.0  # [Hz] Publish state frequency 
    state_machine_tick_freq: 50.0  # [Hz] Frequency to tick state machine
    pub_ctrl_freq: 50.0  # [Hz] Publish control input command frequency