/**:
  ros__parameters:
    # Available trajectory types: MINCO, MPC
    trajectory_type: MPC

    # Safety params
    navigator_heartbeat_timeout: 0.5  # [s] Timeout for navigator heartbeat

    # Frequency for timers
    set_offb_ctrl_freq: 5.0  #[ Hz] Offboard control mode publish frequency
    pub_state_freq: 50.0  # [Hz] Publish state frequency 
    state_machine_tick_freq: 50.0  # [Hz] Frequency to tick state machine
    pub_ctrl_freq: 100.0  # [Hz] Publish control input command frequency