/**:
  ros__parameters:
    # Safety params
    safety:
      navigator_state_timeout: 0.5  # [s] Timeout for navigator heartbeat
      geofence: # [m] Geofence around world origin
        min_x: -50.0
        min_y: -50.0
        min_z: -0.5
        max_x: 50.0
        max_y: 50.0
        max_z: 5.0

    # Frequency for timers
    set_offb_ctrl_freq: 5.0  #[ Hz] Offboard control mode publish frequency
    pub_state_freq: 50.0  # [Hz] Publish state frequency 
    state_machine_tick_freq: 30.0  # [Hz] Frequency to tick state machine
    pub_ctrl_freq: 30.0  # [Hz] Publish control input command frequency